#include <cstdint>
#include "export_ps2recomp.h"
#include "sqlite3.h"
#include <sstream>

static std::string categorize_func(const char* name) {
    if (!name) return "game";
    std::string n(name);
    if (n.find("sce") == 0 || n.find("Sif") == 0 || n.find("Gs") == 0 ||
        n.find("Pad") == 0 || n.find("Mc") == 0 || n.find("Cd") == 0 ||
        n.find("Dma") == 0 || n.find("Vif") == 0 || n.find("Gif") == 0 ||
        n.find("Mpeg") == 0 || n.find("Spu") == 0 || n.find("Iop") == 0 ||
        n.find("Vpu") == 0) {
        return "sdk";
    }
    if (n.find("sub_") == 0 || n.find("loc_") == 0) return "unknown";
    return "named";
}

std::string export_ps2recomp_toml(const std::string& db_path, const std::string& elf_name) {
    sqlite3* db = nullptr;
    if (sqlite3_open(db_path.c_str(), &db) != SQLITE_OK) {
        return "-- ERROR: Cannot open database";
    }

    std::ostringstream toml;
    toml << "# PS2Recomp - " << elf_name << "\n# Generated by recomp-tool\n\n";
    toml << "[general]\n";
    toml << "input = \"" << elf_name << "\"\n";
    toml << "ghidra_output = \"\"\n";
    toml << "output = \"./output/\"\n";
    toml << "single_file_output = false\n";
    toml << "patch_syscalls = false\n";
    toml << "patch_cop0 = true\n";
    toml << "patch_cache = true\n\n";

    // SDK stubs
    toml << "stubs = [\n";
    sqlite3_stmt* stmt = nullptr;
    std::string q = "SELECT name, address FROM functions WHERE category = 'sdk' ORDER BY name";
    if (sqlite3_prepare_v2(db, q.c_str(), -1, &stmt, nullptr) == SQLITE_OK) {
        while (sqlite3_step(stmt) == SQLITE_ROW) {
            const char* name = (const char*)sqlite3_column_text(stmt, 0);
            uint64_t addr = sqlite3_column_int64(stmt, 1);
            char hex[32];
            snprintf(hex, sizeof(hex), "0x%08X", (uint32_t)addr);
            toml << "  \"" << (name ? name : "unknown") << "@" << hex << "\",\n";
        }
        sqlite3_finalize(stmt);
    }
    toml << "]\n\n";
    toml << "untracked_stubs = []\n";
    toml << "skip = []\n";

    sqlite3_close(db);
    return toml.str();
}

std::string export_ps2recomp_csv(const std::string& db_path, const std::string& elf_name) {
    sqlite3* db = nullptr;
    if (sqlite3_open(db_path.c_str(), &db) != SQLITE_OK) {
        return "ERROR: Cannot open database";
    }

    std::ostringstream csv;
    csv << "Name,Start,End,Size\n";

    sqlite3_stmt* stmt = nullptr;
    std::string q = "SELECT name, address, size FROM functions ORDER BY address";
    if (sqlite3_prepare_v2(db, q.c_str(), -1, &stmt, nullptr) == SQLITE_OK) {
        while (sqlite3_step(stmt) == SQLITE_ROW) {
            const char* name = (const char*)sqlite3_column_text(stmt, 0);
            uint64_t addr = sqlite3_column_int64(stmt, 1);
            uint64_t size = sqlite3_column_int64(stmt, 2);
            char start_hex[32], end_hex[32];
            snprintf(start_hex, sizeof(start_hex), "0x%08X", (uint32_t)addr);
            snprintf(end_hex, sizeof(end_hex), "0x%08X", (uint32_t)(addr + size));
            csv << (name ? name : "unknown") << "," << start_hex << "," << end_hex << "," << size << "\n";
        }
        sqlite3_finalize(stmt);
    }

    sqlite3_close(db);
    return csv.str();
}
